# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Output deno version
        run: |
          deno --version
        working-directory: typescript/deno/discord
          
      - name: Lint
        run: deno lint --unstable
        working-directory: typescript/deno/discord
        
      - name: Unit tests
        run: deno test --allow-env --allow-read
        working-directory: typescript/deno/discord
